

<div class="center_content">
			<div class="banner">
				<div class="bannerslides"><img src="../img/banner1.png" alt="petmatchup" /></div>
			</div>
			
			
			
			<!--Dogs Section-->
			<div id="dogs">
				<h2>Real dogs looking for playdates</h2>
				<div class="dogimg"><a href="details.html"><img src="../img/dog1.gif" /></a></div>
				<div class="dogimg"><a href="details.html"><img src="../img/dog2.gif" /></a></div>
				<div class="dogimg"><a href="details.html"><img src="../img/dog3.gif" /></a></div>
				<div class="dogimg"><a href="details.html"><img src="../img/dog4.gif" /></a></div>
				<div class="dogimg" style="margin-right:0px;"><a href="details.html"><img src="../img/dog5.gif" /></a></div>
				<div class="clear"></div>
			</div>
			
			
			
			
			<!--Video Section-->
			<div id="mainbody">
				<div class="videosection">
					<h2>Sign Up Now</h2><a name="signin-form"></a>
					<div class="signupform">
						<div class="leftform">
							<h2>Sign-in to your account</h2>
							
							<div class="signin-section">
								<div class="login-form"><?php echo $this->SignIn; ?></div>
								<div class="forgot-password"><a id="editprofile" href="<?php echo $this->url(array('controller' =>'sign-up','action'  => 'recover-password')); ?>">Forget Password</a></div>
							</div>
													
						</div>
						<div class="rightform">
							<h2>Create an account</h2>
							<p>Please create an account and find a brand new way for you and your dog to meet new friends in your neighborhood</p>
							<div class="create-button">
                				<?php if(isset($this->SignUpError)) { echo $this->SignUpError; }?> 
                				<a href="sign-up" class="createaccount">Create Account</a>
							</div>
						</div>
						<div class="clear"></div>
					</div>
				</div>
				<div class="mapsection">
					<h2>Search Location</h2>
					<input name="" placeholder="Search Location here" type="text" />
					<div class="button"><a href="#" title="Search Now!">Search</a></div>
					<div class="clear"></div>
					
					<div class="googlemap">
						<iframe width="350" height="200" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=Pet+Match+Up&amp;sll=37.0625,-95.677068&amp;sspn=54.005807,79.013672&amp;ie=UTF8&amp;hq=Pet+Match+Up&amp;hnear=&amp;t=m&amp;ll=37.020098,-95.625&amp;spn=41.667373,61.523438&amp;z=3&amp;output=embed"></iframe>
					</div>
					
				</div>
				<div class="clear"></div>
			</div>
			
			
			
			
			
			
       	<div class="left_content">
        	
            <div class="title"><span class="title_icon"><img src="../img/bullet1.gif" alt="" title="" /></span>Welcome to Petmatchup</div>
        
        	<div class="feat_prod_box">
            
            	<div class="prod_img"><a href="details.html"><img src="../img/prod1.gif" alt="" title="" border="0" /></a></div>
                
                <div class="prod_det_box">
                	<div class="box_top"></div>
                    <div class="box_center">
                    <div class="prod_title">What is petmatchup</div>
                    <p class="details">Petmatchup is a website that is being designed and developed, having the purpose in mind of providing the means to create and keep open a line of communication among people who love pets, or so called pet lovers.

We hope to create a network of pet lovers, a niche, where they can relate to each other and provide to themselves the information required to take good care of the pet.</p>
                    <a href="details.html" class="more">- more details -</a>
                    <div class="clear"></div>
                    </div>
                    
                    <div class="box_bottom"></div>
                </div>    
            <div class="clear"></div>
            </div>	
            
            
        	<div class="feat_prod_box">
            
            	<!--<div class="prod_img"><a href="details.html"><img src="../img/prod2.gif" alt="" title="" border="0" /></a></div>
                -->
                <div class="prod_det_box">
                	<!--<div class="box_top"></div> -->
                    <div class="box_center">
                 <!--   <div class="prod_title">Yes, its still FREE...</div>
                   <p class="details">PETMATCHUP was created to provide a means of communication between pet lovers and other like-minded individuals.This website is currently a free pet social networking and mate selection service. Stud your dog today!</p>
                  
                    <a href="details.html" class="more">- more details -</a>
                    -->
                    <div class="clear"></div>
                    </div>
                    
                   <!-- <div class="box_bottom"></div> -->
                </div>    
            <div class="clear"></div>
            </div>      
            
            
			
			
            
           <div class="title"><span class="title_icon"><img src="../img/bullet2.gif" alt="" title="" /></span>New pets</div> 
           
           <div class="new_products">
           
                    <div class="new_prod_box">
                        <a href="details.html">Pet Name</a>
                        <div class="new_prod_bg">
                        <span class="new_icon"><img src="../img/new_icon.gif" alt="" title="" /></span>
                        <a href="details.html"><img src="../img/thumb1.gif" alt="" title="" class="thumb" border="0" /></a>
                        </div>           
                    </div>
                    
                    <div class="new_prod_box">
                        <a href="details.html">Pet Name</a>
                        <div class="new_prod_bg">
                        <span class="new_icon"><img src="../img/new_icon.gif" alt="" title="" /></span>
                        <a href="details.html"><img src="../img/thumb2.gif" alt="" title="" class="thumb" border="0" /></a>
                        </div>           
                    </div>                    
                    
                    <div class="new_prod_box">
                        <a href="details.html">Pet Name</a>
                        <div class="new_prod_bg">
                        <span class="new_icon"><img src="../img/new_icon.gif" alt="" title="" /></span>
                        <a href="details.html"><img src="../img/thumb3.gif" alt="" title="" class="thumb" border="0" /></a>
                        </div>           
                    </div>          
            
            </div> 
          
            
        <div class="clear"></div>
        </div><!--end of left content-->
        
        <div class="right_content">
        	<div class="languages_box">
            <span class="red">Languages:</span>
            <a href="#" class="selected"><img src="../img/gb.gif" alt="" title="" border="0" /></a>
            <a href="#"><img src="../img/fr.gif" alt="" title="" border="0" /></a>
            <a href="#"><img src="../img/de.gif" alt="" title="" border="0" /></a>
            
            
            </div>
            <br />
            <br />
            <?php if(!Zend_Auth::getInstance()->hasIdentity()): ?>


            
            

            <?php endif; ?>
             
                <!--<div class="currency">
                <span class="red">Currency: </span>
                <a href="#">GBP</a>
                <a href="#">EUR</a>
                <a href="#" class="selected">USD</a>
                </div> -->
                
                
            <div class="cart">
                  
                  <div class="home_cart_content">
                  <span class="red"></span>
                  </div>
                  <a href="cart.html" class="view_cart"></a>
              
              </div> 
                       
            	
        
        
             <div class="title"><span class="title_icon"><img src="../img/bullet3.gif" alt="" title="" /></span>Yes, its still FREE...</div> 
             <div class="about">
             <p>
             <img src="../img/about.gif" alt="" title="" class="right" />
             PETMATCHUP was created to provide a means of communication between pet lovers and other like-minded individuals.This website is currently a free pet social networking and mate selection service. Stud your dog today!
             </p>
             
             </div>
             
             <div class="right_box">
             
             	<div class="title"><span class="title_icon"><img src="../img/bullet4.gif" alt="" title="" /></span>Promoted Pet</div> 
                    <div class="new_prod_box">
                        <a href="details.html">pet name</a>
                        <div class="new_prod_bg">
                        <span class="new_icon"><img src="../img/promo_icon.gif" alt="" title="" /></span>
                        <a href="details.html"><img src="../img/thumb1.gif" alt="" title="" class="thumb" border="0" /></a>
                        </div>           
                    </div>
                    
                    <div class="new_prod_box">
                        <a href="details.html">pet name</a>
                        <div class="new_prod_bg">
                        <span class="new_icon"><img src="../img/promo_icon.gif" alt="" title="" /></span>
                        <a href="details.html"><img src="../img/thumb2.gif" alt="" title="" class="thumb" border="0" /></a>
                        </div>           
                    </div>                    
                    
                    <div class="new_prod_box">
                        <a href="details.html">pet name</a>
                        <div class="new_prod_bg">
                        <span class="new_icon"><img src="../img/promo_icon.gif" alt="" title="" /></span>
                        <a href="details.html"><img src="../img/thumb3.gif" alt="" title="" class="thumb" border="0" /></a>
                        </div>           
                    </div>              
             
             </div>
             
             <div class="right_box">
             
             	<div class="title"><span class="title_icon"><img src="../img/bullet5.gif" alt="" title="" /></span>Categories</div> 
                
                <ul class="list">
                <li><a href="#">accesories</a></li>
                <li><a href="#">pets gifts</a></li>
                <li><a href="#">specials</a></li>
                <li><a href="#">hollidays gifts</a></li>
                <li><a href="#">accesories</a></li>
                <li><a href="#">pets gifts</a></li>
                <li><a href="#">specials</a></li>
                <li><a href="#">hollidays gifts</a></li>
                <li><a href="#">accesories</a></li>
                <li><a href="#">pets gifts</a></li>
                <li><a href="#">specials</a></li>                                              
                </ul>
                
             	<div class="title"><span class="title_icon"><img src="../img/bullet6.gif" alt="" title="" /></span>Partners</div> 
                
                <ul class="list">
                <li><a href="#">accesories</a></li>
                <li><a href="#">pets gifts</a></li>
                <li><a href="#">specials</a></li>
                <li><a href="#">hollidays gifts</a></li>
                <li><a href="#">accesories</a></li>
                <li><a href="#">pets gifts</a></li>
                <li><a href="#">specials</a></li>
                <li><a href="#">hollidays gifts</a></li>
                <li><a href="#">accesories</a></li>                              
                </ul>      
             
             </div>         
             
        
        </div><!--end of right content-->
        
        
       
       
       <div class="clear"></div>
       </div><!--end of center content-->