

<div class="center_content">
       	<div class="left_content">
        	
  <div class="center_content">
       	<div class="left_content">
            <div class="title"><span class="title_icon"><img src="../img/bullet1.gif" alt="" title="" /></span>Contact Us</div>

            
<div class="contact_form">
     <div class="form_subtitle">All fields are requierd</div>          
          <div class="form_row">
  
    <?php     echo $this->form; ?>
         </div>      
</div>
     <div class="clear"></div>
        </div>
    
        
        
            <div class="clear"></div>
       </div><!--end of center content-->
        
                      
        
            
              
            
           
            
              
        <div class="clear"></div>
        </div><!--end of left content-->
        
        <div class="right_content">
        	<div class="languages_box">
            <span class="red">Languages:</span>
            <a href="#" class="selected"><img src="../img/gb.gif" alt="" title="" border="0" /></a>
            <a href="#"><img src="../img/fr.gif" alt="" title="" border="0" /></a>
            <a href="#"><img src="../img/de.gif" alt="" title="" border="0" /></a>
            
            
            </div>
            
             
                <!--<div class="currency">
                <span class="red">Currency: </span>
                <a href="#">GBP</a>
                <a href="#">EUR</a>
                <a href="#" class="selected">USD</a>
                </div> -->
                
                
            <div class="cart">
                  
                  <div class="home_cart_content">
                  <span class="red"></span>
                  </div>
                  <a href="cart.html" class="view_cart"></a>
              
              </div> 
                       
            	
        
        
             <div class="title"><span class="title_icon"><img src="../img/bullet3.gif" alt="" title="" /></span>Yes, its still FREE...</div> 
             <div class="about">
             <p>
             <img src="../img/about.gif" alt="" title="" class="right" />
             PETMATCHUP was created to provide a means of communication between pet lovers and other like-minded individuals.This website is currently a free pet social networking and mate selection service. Stud your dog today!
             </p>
             
             </div>
             
             <div class="right_box">
             
             	<div class="title"><span class="title_icon"><img src="../img/bullet4.gif" alt="" title="" /></span>Promoted Pet</div> 
                    <div class="new_prod_box">
                        <a href="details.html">pet name</a>
                        <div class="new_prod_bg">
                        <span class="new_icon"><img src="../img/promo_icon.gif" alt="" title="" /></span>
                        <a href="details.html"><img src="../img/thumb1.gif" alt="" title="" class="thumb" border="0" /></a>
                        </div>           
                    </div>
                    
                    <div class="new_prod_box">
                        <a href="details.html">pet name</a>
                        <div class="new_prod_bg">
                        <span class="new_icon"><img src="../img/promo_icon.gif" alt="" title="" /></span>
                        <a href="details.html"><img src="../img/thumb2.gif" alt="" title="" class="thumb" border="0" /></a>
                        </div>           
                    </div>                    
                    
                    <div class="new_prod_box">
                        <a href="details.html">pet name</a>
                        <div class="new_prod_bg">
                        <span class="new_icon"><img src="../img/promo_icon.gif" alt="" title="" /></span>
                        <a href="details.html"><img src="../img/thumb3.gif" alt="" title="" class="thumb" border="0" /></a>
                        </div>           
                    </div>              
             
             </div>
             
             <div class="right_box">
             
             	<div class="title"><span class="title_icon"><img src="../img/bullet5.gif" alt="" title="" /></span>Categories</div> 
                
                <ul class="list">
                <li><a href="#">accesories</a></li>
                <li><a href="#">pets gifts</a></li>
                <li><a href="#">specials</a></li>
                <li><a href="#">hollidays gifts</a></li>
                <li><a href="#">accesories</a></li>
                <li><a href="#">pets gifts</a></li>
                <li><a href="#">specials</a></li>
                <li><a href="#">hollidays gifts</a></li>
                <li><a href="#">accesories</a></li>
                <li><a href="#">pets gifts</a></li>
                <li><a href="#">specials</a></li>                                              
                </ul>
                
             	<div class="title"><span class="title_icon"><img src="../img/bullet6.gif" alt="" title="" /></span>Partners</div> 
                
                <ul class="list">
                <li><a href="#">accesories</a></li>
                <li><a href="#">pets gifts</a></li>
                <li><a href="#">specials</a></li>
                <li><a href="#">hollidays gifts</a></li>
                <li><a href="#">accesories</a></li>
                <li><a href="#">pets gifts</a></li>
                <li><a href="#">specials</a></li>
                <li><a href="#">hollidays gifts</a></li>
                <li><a href="#">accesories</a></li>                              
                </ul>      
             
             </div>         
             
        
        </div><!--end of right content-->
        
        
       
       
       <div class="clear"></div>
       </div><!--end of center content-->


