<div class="footer">
       	<!--<div class="left_footer">
        <img src="../img/footer_logo.gif" alt="" title="" /><br /> 
        <a href="http://csscreme.com/freecsstemplates/" title="free css templates">
        <img src="../img/csscreme.gif" alt="free css templates" border="0" /></a></div> -->
        <div class="right_footer">
        <a href="#">home</a>
        <a href="#">about us</a>
        <a href="#">services</a>
        <a href="#">privacy policy</a>
        <a href="#">contact us</a>
       
        </div>
        
       
       </div>
</div>


    </body>

</html>