<div class="center_content">
       	<div class="left_content">
            <div class="title"><span class="title_icon"><img src="../img/bullet1.gif" alt="" title="" /></span>Contact Us</div>

<div class="contact_form">
                <div class="form_subtitle">All fields are requierd</div>          
                    <div class="form_row">
<?php echo $this->form; ?>



    			</div>      
                    
</div>
            <div class="clear"></div>
        </div>
    <div class="right_content">
        hello world
        </div>
            <div class="clear"></div>
       </div><!--end of center content-->
            
         
          	