<?php foreach($this->petDetails as $pd): ?>
<ul>

	<strong>Name</strong><li> <?php	echo $pd['name'];  ?></li>
	<strong>Type</strong><li> 
	<?php	
	// echo $pd['type'];
			$profileType = new Application_Model_ProfileType();
			$where = 'id = '. $pd['type'];
			$ptype = $profileType->fetchAll($where)->toArray();
			foreach($ptype as $pt):
			echo $pt['name'];
			endforeach;
	 ?>
	 </li>
	
	
	<strong>State</strong><li><?php

		if(is_numeric($pd['state'])):
		
			$getStates = new Application_Model_State();	
			$where = 'state_id = '. $pd['state'];
			$stateResult = $getStates->fetchAll($where)->toArray();
			foreach($stateResult as $value):
			echo $value['state'];
			endforeach;
			//$stateResult = $getStates->fetchAll("state_id =".$pd['state'])->toArray();

			// foreach ($stateResult as $value){echo "hello".$stateRow = $value['state'];}
         
        else:
        
        	echo $pd['state'];
        endif;

				?>
	</li>
	<strong>Country</strong><li> <?php  if(isset($pd['country'])) 
	{
		if($pd['country'] == 1)
		{
			echo "America";
		}
		else
		{
			echo "Canada";
		}
    }
    ?></li>
 	
 	<strong>City</strong> <?php  if(isset($pd['city'])) {	echo "<li>".$pd['city']."</li>"; }?>
 	
 	<strong>Race</strong> <?php	echo "<li>".$pd['race']."</li>";  ?>

	<strong>Amount</strong><?php  echo "<li>".$pd['amount']."</li>"; ?>
	
	<strong>Sex</strong> <?php  echo "<li>".$pd['sex']."</li>"; ?>
    
    <strong>Papers</strong> <?php  if($pd['papers'] == '1'){ echo "<li>".'Yes'."</li>";}else{ echo "<li>".'No'."</li>";} ?>
   
   <strong> Negotiable</strong><?php  if($pd['negotiable'] == '1') { echo "<li>".'Yes'."</li>"; }else{ echo "<li>".'No'."</li>"; } ?>
   
    <strong>Details</strong> <?php  echo "<li>".$pd['details']."</li>"; ?>
     


  <?php if(isset($this->petPics)): ?>
  <?php foreach($this->petPics as $pp): ?>
  
  <img src="/images/<?php echo $pp['picture'];  ?>" height="100" width="120" />
  
      
   
	    <?php endforeach; ?>
	  <?php endif; ?>
 
</ul>
<?php if(!isset($this->trueVal)) 
{
 echo "<button>Contact Person</button>";
}
 ?>
<div id="captcha" style="display: none"><?php echo $this->captchaForm; ?></div>
<?php if(isset($this->trueVal)){
	   
	   echo "<ul><li><strong>". $pd['email']. "</strong></li></ul>"; 
	   echo "<ul><li><strong>". $pd['phone']. "</strong></li></ul>";
}

	  
 ?>
 <?php endforeach; ?>

