

<div class="center_content">
			

       	<div class="left_content">
        	
            <div class="title"><span class="title_icon"><img src="../img/bullet1.gif" alt="" title="" /></span>Welcome to Petmatchup</div>
        
        	<div class="feat_prod_box">
            
            	<div class="prod_img"><a href="details.html"><img src="../img/prod1.gif" alt="" title="" border="0" /></a></div>
                
                <div class="prod_det_box">
                	<div class="box_top"></div>
                    <div class="box_center">
                    <div class="prod_title">What is petmatchup</div>
                    <p class="details">Petmatchup is a website that is being designed and developed, having the purpose in mind of providing the means to create and keep open a line of communication among people who love pets, or so called pet lovers.

We hope to create a network of pet lovers, a niche, where they can relate to each other and provide to themselves the information required to take good care of the pet.</p>
                    <a href="details.html" class="more">- more details -</a>
                    <div class="clear"></div>
                    </div>
                    
                    <div class="box_bottom"></div>
                </div>    
            <div class="clear"></div>
            </div>	
            
            
        	<div class="feat_prod_box">
            
            	<!--<div class="prod_img"><a href="details.html"><img src="../img/prod2.gif" alt="" title="" border="0" /></a></div>
                -->
                <div class="prod_det_box">
                	<!--<div class="box_top"></div> -->
                    <div class="box_center">
                 <!--   <div class="prod_title">Yes, its still FREE...</div>
                   <p class="details">PETMATCHUP was created to provide a means of communication between pet lovers and other like-minded individuals.This website is currently a free pet social networking and mate selection service. Stud your dog today!</p>
                  
                    <a href="details.html" class="more">- more details -</a>
                    -->
                    <div class="clear"></div>
                    </div>
                    
                   <!-- <div class="box_bottom"></div> -->
                </div>    
            <div class="clear"></div>
            </div>      
            
            
            
           <div class="title"><span class="title_icon"><img src="../img/bullet2.gif" alt="" title="" /></span>New pets</div> 
           
           <div class="new_products">
           
                    <div class="new_prod_box">
                        <a href="details.html">Pet Name</a>
                        <div class="new_prod_bg">
                        <span class="new_icon"><img src="../img/new_icon.gif" alt="" title="" /></span>
                        <a href="details.html"><img src="../img/thumb1.gif" alt="" title="" class="thumb" border="0" /></a>
                        </div>           
                    </div>
                    
                    <div class="new_prod_box">
                        <a href="details.html">Pet Name</a>
                        <div class="new_prod_bg">
                        <span class="new_icon"><img src="../img/new_icon.gif" alt="" title="" /></span>
                        <a href="details.html"><img src="../img/thumb2.gif" alt="" title="" class="thumb" border="0" /></a>
                        </div>           
                    </div>                    
                    
                    <div class="new_prod_box">
                        <a href="details.html">Pet Name</a>
                        <div class="new_prod_bg">
                        <span class="new_icon"><img src="../img/new_icon.gif" alt="" title="" /></span>
                        <a href="details.html"><img src="../img/thumb3.gif" alt="" title="" class="thumb" border="0" /></a>
                        </div>           
                    </div>          
            
            </div> 
          
            
        <div class="clear"></div>
        </div><!--end of left content-->
        
        <div class="right_content">
        	<div class="languages_box">
            <span class="red">Languages:</span>
            <a href="#" class="selected"><img src="../img/gb.gif" alt="" title="" border="0" /></a>
            <a href="#"><img src="../img/fr.gif" alt="" title="" border="0" /></a>
            <a href="#"><img src="../img/de.gif" alt="" title="" border="0" /></a>
            
            
            </div>
            <br />
            <br />
            <div>
                <?php echo $this->SignIn; ?>
            </div>
                <!--<div class="currency">
                <span class="red">Currency: </span>
                <a href="#">GBP</a>
                <a href="#">EUR</a>
                <a href="#" class="selected">USD</a>
                </div> -->
                
                
            <div class="cart">
                  
                  <div class="home_cart_content">
                  <span class="red"></span>
                  </div>
                  <a href="cart.html" class="view_cart"></a>
              
              </div> 
                       
            	
        
        
             <div class="title"><span class="title_icon"><img src="../img/bullet3.gif" alt="" title="" /></span>Yes, its still FREE...</div> 
             <div class="about">
             <p>
             <img src="../img/about.gif" alt="" title="" class="right" />
             PETMATCHUP was created to provide a means of communication between pet lovers and other like-minded individuals.This website is currently a free pet social networking and mate selection service. Stud your dog today!
             </p>
             
             </div>
             
             <div class="right_box">
             
             	<div class="title"><span class="title_icon"><img src="../img/bullet4.gif" alt="" title="" /></span>Promoted Pet</div> 
                    <div class="new_prod_box">
                        <a href="details.html">pet name</a>
                        <div class="new_prod_bg">
                        <span class="new_icon"><img src="../img/promo_icon.gif" alt="" title="" /></span>
                        <a href="details.html"><img src="../img/thumb1.gif" alt="" title="" class="thumb" border="0" /></a>
                        </div>           
                    </div>
                    
                    <div class="new_prod_box">
                        <a href="details.html">pet name</a>
                        <div class="new_prod_bg">
                        <span class="new_icon"><img src="../img/promo_icon.gif" alt="" title="" /></span>
                        <a href="details.html"><img src="../img/thumb2.gif" alt="" title="" class="thumb" border="0" /></a>
                        </div>           
                    </div>                    
                    
                    <div class="new_prod_box">
                        <a href="details.html">pet name</a>
                        <div class="new_prod_bg">
                        <span class="new_icon"><img src="../img/promo_icon.gif" alt="" title="" /></span>
                        <a href="details.html"><img src="../img/thumb3.gif" alt="" title="" class="thumb" border="0" /></a>
                        </div>           
                    </div>              
             
             </div>
             
             <div class="right_box">
             
             	<div class="title"><span class="title_icon"><img src="../img/bullet5.gif" alt="" title="" /></span>Categories</div> 
                
                <ul class="list">
                <li><a href="#">accesories</a></li>
                <li><a href="#">pets gifts</a></li>
                <li><a href="#">specials</a></li>
                <li><a href="#">hollidays gifts</a></li>
                <li><a href="#">accesories</a></li>
                <li><a href="#">pets gifts</a></li>
                <li><a href="#">specials</a></li>
                <li><a href="#">hollidays gifts</a></li>
                <li><a href="#">accesories</a></li>
                <li><a href="#">pets gifts</a></li>
                <li><a href="#">specials</a></li>                                              
                </ul>
                
             	<div class="title"><span class="title_icon"><img src="../img/bullet6.gif" alt="" title="" /></span>Partners</div> 
                
                <ul class="list">
                <li><a href="#">accesories</a></li>
                <li><a href="#">pets gifts</a></li>
                <li><a href="#">specials</a></li>
                <li><a href="#">hollidays gifts</a></li>
                <li><a href="#">accesories</a></li>
                <li><a href="#">pets gifts</a></li>
                <li><a href="#">specials</a></li>
                <li><a href="#">hollidays gifts</a></li>
                <li><a href="#">accesories</a></li>                              
                </ul>      
             
             </div>         
             
        
        </div><!--end of right content-->
        
        
       
       
       <div class="clear"></div>
       </div><!--end of center content-->